# Generated by Django 5.2.7 on 2025-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/avatar/', verbose_name='تصویر آواتار'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default=1, max_length=100, verbose_name='کد فعالسازی ایمیل'),
            preserve_default=False,
        ),
    ]
