# Generated by Django 5.2.7 on 2025-10-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='username',
        ),
    ]
