# Generated by Django 5.2.7 on 2025-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_remove_contactus_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
