# Generated by Django 5.2.7 on 2025-10-10 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('author', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('poster', models.ImageField(blank=True, upload_to='books/', verbose_name='عکس')),
                ('short_description', models.CharField(max_length=20, verbose_name='توضیحات کوتاه')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت')),
                ('discount', models.CharField(blank=True, max_length=50, null=True, verbose_name='تخفیف')),
                ('price_after_discount', models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت بعد از تخفیف')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('status', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('is_available', models.BooleanField(verbose_name='موجود است/نیست')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
    ]
