# Generated by Django 5.2.7 on 2025-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='books',
            name='poster',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/books/', verbose_name='عکس'),
        ),
    ]
