# Generated by Django 5.2.7 on 2025-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_status_books_is_active_remove_books_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='انتشارات'),
        ),
        migrations.AddField(
            model_name='books',
            name='translator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مترجم'),
        ),
    ]
