# Generated by Django 5.2.7 on 2025-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_books_language_books_publisher_books_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='body',
            field=models.TextField(db_index=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.CharField(max_length=50, verbose_name='قیمت به هزار تومان'),
        ),
        migrations.AlterField(
            model_name='books',
            name='short_description',
            field=models.CharField(db_index=True, max_length=20, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام'),
        ),
    ]
